### ISSUE TITLE
install failing on kubernetes 1.17

### ISSUE THREAD

**Issue by thedewpoint** [concourse/concourse-chart#103] opened 2020-05-20 02:07 UTC
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

**Comment by kivio** [comment] 2020-06-15 15:05
it works with chart 11.1.0 ;)

**Comment by taylorsilva** [comment] 2020-07-09 16:08
I'm closing this because:
* no reproducible steps provided
* no one else is reporting this issue

**Closed by taylorsilva** 2020-07-09 16:08 UTC

**Comment by poblin-orange** [comment] 2020-07-21 17:08
Hello,
met the same issue today with k8s 1.18.5, concourse chart 11.4.0 (same on  11.2.3)

```
           first try failed: helm upgrade --install  --version=11.2.3 --namespace concourse concourse concourse/concourse  -f /tmp/chart_concourse.yml                                                                                                                                                                                                                                                                                                                                                                             
           Release "concourse" does not exist. Installing it now.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
           coalesce.go:196: warning: cannot overwrite table with non table for updateStrategy (map[type:RollingUpdate])                                                                                                                                                                                                                                                                                                                                                                                                           
           coalesce.go:196: warning: cannot overwrite table with non table for updateStrategy (map[type:RollingUpdate])                                                                                                                                                                                                                                                                                                                                                                                                            
           Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.updateStrategy): invalid type for io.k8s.api.apps.v1.StatefulSetUpdateStrategy: got "string", expected "map"                                                                                                                                                                                                                                                              
		Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.updateStrategy): invalid type for io.k8s.api.apps.v1.StatefulSetUpdateStrategy: got "string", expected "map" 
```

Our context:
- S&W k8s bosh release, k8s v1.18.5 https://github.com/jhunt/k8s-boshrelease/releases/tag/v1.18.5-build.1
- using helm 3 client, packaged in  https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease

Helm chart version 9.1.0 is OK ...

**Comment by taylorsilva** [comment] 2020-07-24 16:14
The error here is different, looks like a structural difference made in k8s 1.18. From your error:

```
invalid type for io.k8s.api.apps.v1.StatefulSetUpdateStrategy: got "string", expected "map"
```

I'm going to open a separate issue for this.

**Comment by outworlder** [comment] 2021-03-11 22:47
@taylorsilva @poblin-orange Hit the same issue.

In my case, this was caused by trying to use an old version of values.yaml file with a newer version of the helm chart.

updateStrategy looks like this on the old version:
```
 updateStrategy: RollingUpdate
```
The newer one looks like:

```
  updateStrategy:
    type: RollingUpdate
```
