### ISSUE TITLE
concourse task wait metrics are missed

### ISSUE THREAD

**Issue by dmytro-zhernosiekov-rft** [concourse/concourse-chart#209] opened 2021-02-18 14:09 UTC
## Summary

There are several metrics missing on our Concourse CI:
`concourse_tasks_waiting_duration`
`concourse_tasks_waiting`
which really important for autoscalling and tracking user pipeline delays

## Steps to reproduce

Deploy Concourse CI with Helm chart:
```
variable "concourse_version" {
  type        = string
  description = "Concourse release."
  default     = "6.7.5"
}

variable "helm_chart_version" {
  type    = string
  default = "11.4.1"
}
```

## Expected results

concourse_tasks_watingin metrics appeared on prometheus service endpoint.

## Actual results
Port forward:
```
kubectl port-forward service/concourse-web-prometheus -n concourse 9391:9391
Forwarding from 127.0.0.1:9391 -> 9391
Handling connection for 9391
Handling connection for 9391
```
In terminal:
```
$> curl http://localhost:9391/ | grep wait
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
dmytro@centos: ~/Documents/refi/sdp-app-deploy $> 

```
Other metrics are present.

## Additional context

Concourse run in AWS EKS, deployed with Helm Chart.

## Triaging info

* Concourse version: 6.7.5
* Browser (if applicable):  does not matter
* Did this used to work? no

**Comment by taylorsilva** [comment] 2021-02-23 16:44
Duplicate of https://github.com/concourse/concourse/issues/6552
Keeping discussion in concourse/concourse since if there is an issue, it's probably not in the helm chart.

**Closed by taylorsilva** 2021-02-23 16:44 UTC
